sudo: required
dist: precise
language: python
python:
  - 3.4
  - 3.5

install:
  - bash setup.sh
  - cd website
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt

script:
  - python3 -m pytest -k 'not data_dependent'
  - python3 -m pytest --cov=. -k 'not data_dependent'


after_success:
    coveralls
