sudo: required
dist: trusty
language: python
cache:
  timeout: 1800
  pip: true
  directories:
    - node_modules
    - downloads

python:
  - 3.4
  - 3.5

install:
  - sudo apt-get update
  - sudo apt-get install -y pigz npm
  - bash setup.sh
  - cd website
  - pip install wheel
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - sass --update .:.

script:
  - python3 -m pytest -x -n 2 --cov=. -k 'not data_dependent'


after_success:
  - cd ..
  - coveralls --data_file website/.coverage --config_file=website/.coveragerc
